/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Propiedad } from './types';

export const INITIAL_PROPERTIES: Propiedad[] = [
  {
    id: 'prop-1',
    titulo: 'Humboldt 2400 - USD 450.000',
    precio: 450000,
    moneda: 'USD',
    expensas: 45000,
    direccion: 'Humboldt 2400',
    barrio: 'Palermo Soho',
    m2_totales: 120,
    m2_cubiertos: 110,
    ambientes: 3,
    dormitorios: 2,
    banos: 2,
    orientacion: 'Norte',
    piso: '12º',
    tiene_ascensor: true,
    antiguedad: 'A estrenar',
    fotos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80'
    ],
    descripcion: 'Excelente iluminación natural por la tarde. Ideal para home office. Gran terraza privada.',
    url_original: 'https://www.zonaprop.com.ar/propiedades/penthouse-lujo-palermo-soho.html',
    plataforma: 'zonaprop',
    estado: 'Contactado',
    contactado: true,
    calificacion: 5,
    notas: 'Excelente ubicación. Muy luminoso, con hermosa terraza. Ya agendamos segunda visita.',
    lat: 32, // Percentage on grid top
    lng: 45, // Percentage on grid left
    fecha_agregado: '2026-06-10'
  },
  {
    id: 'prop-2',
    titulo: 'Serrano 1200 - USD 285.000',
    precio: 285000,
    moneda: 'USD',
    expensas: 35000,
    direccion: 'Serrano 1200',
    barrio: 'San Telmo',
    m2_totales: 68,
    m2_cubiertos: 65,
    ambientes: 2,
    dormitorios: 1,
    banos: 1,
    orientacion: 'Norte',
    piso: '2º / Norte',
    tiene_ascensor: true,
    antiguedad: '5 años',
    fotos: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80'
    ],
    descripcion: 'Pisos de cemento alisado, paredes de ladrillo a la vista y carpinterías de hierro originales.',
    url_original: 'https://www.argenprop.com/propiedades/loft-industrial-san-telmo.html',
    plataforma: 'argenprop',
    estado: 'Pendiente',
    contactado: false,
    calificacion: 4,
    notas: 'La dueña es super flexible, requiere pulir los detalles de grifería pero el estilo es inmejorable.',
    lat: 52,
    lng: 32,
    fecha_agregado: '2026-06-11'
  },
  {
    id: 'prop-3',
    titulo: 'Av. Alvear & Ayacucho - USD 1.200',
    precio: 1200,
    moneda: 'USD',
    expensas: 28000,
    direccion: 'Av. Alvear & Ayacucho',
    barrio: 'Recoleta',
    m2_totales: 42,
    m2_cubiertos: 42,
    ambientes: 'Mono.',
    dormitorios: 1,
    banos: 1,
    orientacion: 'Frente',
    piso: '8º / Frente',
    tiene_ascensor: true,
    antiguedad: '10 años',
    fotos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80'
    ],
    descripcion: 'Edificio Francés, techos altos, requiere pulido de pisos. Impecable estado de conservación y equipamiento premium.',
    url_original: 'https://www.mercadolibre.com.ar/inmuebles/estudio-amoblado-recoleta-premium.html',
    plataforma: 'mercadolibre',
    estado: 'Contactado',
    contactado: true,
    calificacion: 3,
    notas: 'Excelente ubicación de prestigio arquitectónico, muy silencioso al contrafrente. Expensas acordes.',
    lat: 68,
    lng: 62,
    fecha_agregado: '2026-06-12'
  },
  {
    id: 'prop-4',
    titulo: 'Amenábar 2200 - USD 320.000',
    precio: 320000,
    moneda: 'USD',
    expensas: 55000,
    direccion: 'Amenábar 2200',
    barrio: 'Belgrano C',
    m2_totales: 95,
    m2_cubiertos: 88,
    ambientes: 3,
    dormitorios: 2,
    banos: 2,
    orientacion: 'Este',
    piso: 'PB',
    tiene_ascensor: true,
    antiguedad: 'A estrenar',
    fotos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80'
    ],
    descripcion: 'Increíble dúplex a estrenar con jardín y parrilla. Muy luminoso, cochera fija cubierta incluida.',
    url_original: 'https://www.zonaprop.com.ar/propiedades/duplex-moderno-belgrano-amenabar.html',
    plataforma: 'zonaprop',
    estado: 'Contactado',
    contactado: true,
    calificacion: 4,
    notas: 'A metros de estación Juramento. Amenities premium como piscina, gimnasio y seguridad remota.',
    lat: 18,
    lng: 78,
    fecha_agregado: '2026-06-13'
  },
  {
    id: 'prop-5',
    titulo: 'Delgado 900 - USD 215.000',
    precio: 215000,
    moneda: 'USD',
    expensas: 25000,
    direccion: 'Delgado 900',
    barrio: 'Colegiales',
    m2_totales: 62,
    m2_cubiertos: 58,
    ambientes: 2,
    dormitorios: 1,
    banos: 1,
    orientacion: 'Oeste',
    piso: '3º',
    tiene_ascensor: true,
    antiguedad: '6 años',
    fotos: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&auto=format&fit=crop&q=80'
    ],
    descripcion: 'Pisos radiantes, caldera individual, balcón corrido al contrafrente con vista a arbolado.',
    url_original: 'https://www.argenprop.com/propiedades/depto-familiar-delgado-colegiales.html',
    plataforma: 'argenprop',
    estado: 'Pendiente',
    contactado: false,
    calificacion: 5,
    notas: 'Muy tranquilo, cercano al Polo Audiovisual, bajas expensas. Cochera de cortesía.',
    lat: 44,
    lng: 18,
    fecha_agregado: '2026-06-14'
  },
  {
    id: 'prop-6',
    titulo: 'Serrano & Loyola - USD 185.000',
    precio: 185000,
    moneda: 'USD',
    expensas: 38000,
    direccion: 'Serrano & Loyola',
    barrio: 'Villa Crespo',
    m2_totales: 55,
    m2_cubiertos: 55,
    ambientes: 1,
    dormitorios: 1,
    banos: 1,
    orientacion: 'Norte',
    piso: 'PB / Interno',
    tiene_ascensor: false,
    antiguedad: '15 años',
    fotos: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&auto=format&fit=crop&q=80'
    ],
    descripcion: 'Ideal inversión para renta temporaria o Airbnb. Muy luminoso a pesar de ser PB por su claraboya vidriada.',
    url_original: 'https://www.mercadolibre.com.ar/inmuebles/loft-villa-crespo-industrial.html',
    plataforma: 'mercadolibre',
    estado: 'Contactado',
    contactado: true,
    calificacion: 3,
    notas: 'Ideal inversión renta temporaria. Muy luminoso a pesar de ser PB.',
    lat: 62,
    lng: 25,
    fecha_agregado: '2026-06-15'
  }
];
